config/routes.rb
Rails.application.routes.draw do
  resources :travels
  resources :welcomes
  mount Ckeditor::Engine => '/ckeditor'
  resources :deposits
  resources :menus
  resources :orders do
    resources :locations
  end
  #get 'orders/orders_index', to: 'orders#orders_index'

  resources :accounts
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  require 'httparty'

  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/order.rb
class Order < ApplicationRecord
  extend FriendlyId
  friendly_id :tracking_number, use: :slugged

  belongs_to :user
  has_many :travels
before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.tracking_number = SecureRandom.random_number(10000000000)
      self.status = false
    end
  end
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  belongs_to :order

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable#, :confirmable, :lockable

has_many :deposits, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :accounts, dependent: :destroy
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/controllers/deposits_controller.rb
class DepositsController < InheritedResources::Base
layout "accounts"
before_action :authenticate_user!
before_action :set_deposits, only: [:show, :edit, :update, :destroy]

def index
  @deposits = Deposit.where(user_id: current_user).order('created_at DESC')
end

def show

end

def new
  @deposit = current_user.deposits.build
end

def create
  @deposit = current_user.deposits.build(deposit_params)
  @deposit.user_id = current_user.id
  respond_to do |format|
    if @deposit.save
      user = User.find_by_id(@deposit.user_id)
      deposit = @deposit
      DepositMailer.deposit_email(user, deposit).deliver
      format.html { redirect_to root_path, notice: 'We have received your deposit request we will contact you soon.' }
      format.json { render :show, status: :created, location: @deposit }
    else
      format.html { render :new }
      format.json { render json: @deposit.errors, status: :unprocessable_entity }
    end
  end
end
private
def set_deposits
  @deposit = Deposit.find(params[:id])
end

def deposit_params
  params.require(:deposit).permit(:payment_type, :amount, :email, :status, :user_id)
end

end

app/controllers/menus_controller.rb
class MenusController < InheritedResources::Base
  before_action :find_menus, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_adminuser!, except: [:index, :show]
  def index
    @menus = Menu.all.order('created_at DESC')
  end

  def show
  end

  private
  def find_menus
    @menu = Menu.friendly.find(params[:id])
  end
    def menu_params
      params.require(:menu).permit(:title, :desc, :body)
    end

end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  layout "accounts", except: [:index, :show]
  before_action :find_order, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_users, only: [:index]

  def index
    @orders = Order.all

    @search = params["search"]
  if @search.present?
    @tracking_number = @search["tracking_number"]
    @orders = Order.where(tracking_number: @tracking_number)
  end
end



  def show
  end
  def new
    @order = current_user.orders.build
  end
  def create
    @order = current_user.orders.build(order_params)
    @order.user_id = current_user.id
    if @order.save
      redirect_to root_path, notice: "Shipment Has Been Lodged Succesfully, We Will Proccess Your Order And Get Back To You Shortly "
    else
      render 'new', notice: "Please Try Again"
    end
  end

  def edit

  end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end

  private


  def find_users
    if params[:id].nil?
      @user = current_user
    end
  end
  def find_order
    @order = Order.friendly.find(params[:id])
  end

    def order_params
      params.require(:order).permit(:first_name, :last_name, :address, :zipcode, :city, :state, :country, :user_id, :phone_number, :slug, :message, :status, :tracking_number)
    end

end

app/controllers/travels_controller.rb
class TravelsController < InheritedResources::Base

  private

    def travel_params
      params.require(:travel).permit(:order_id, :user_id, :arrivaltime, :departtime, :location, :status, :departdate)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/deposits/_form.html.erb
<%= simple_form_for(@deposit) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :payment_type, as: :select, :collection => [ "Bitcoin", "Ethereum", "Moneygram/Western Union", "Bitcoin Cash", "Ria"] %>
    <%= f.input :amount, placeholder: "$5000" %>
    <%= f.input :email, placeholder: "Please Provide Your Registered Email" %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/deposits/edit.html.erb
<h1>Editing Deposit</h1>

<%= render 'form', deposit: @deposit %>

<%= link_to 'Show', @deposit %> |
<%= link_to 'Back', deposits_path %>

app/views/deposits/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="fab fa-btc"></i>
            </div>
            <p class="card-category">BTC/USD</p>
            <!-- code -->
            <% market = 'USDT-BTC'
               url_ticker = 'https://bittrex.com/api/v1.1/public/getticker'
                response = HTTParty.get(url_ticker, query: {market: market})
                result = response["result"]
                @r_last = result["Last"] %>
                <% market = 'USDT-BCH'
                   url_ticker = 'https://bittrex.com/api/v1.1/public/getticker'
                    response = HTTParty.get(url_ticker, query: {market: market})
                    result = response["result"]
                    @bch_last = result["Last"] %>
                    <% market = 'USDT-ETH'
                       url_ticker = 'https://bittrex.com/api/v1.1/public/getticker'
                        response = HTTParty.get(url_ticker, query: {market: market})
                        result = response["result"]
                        @eth_last = result["Last"] %>
            <h3 class="card-title" style="font-size:18px;"><%= @r_last %></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> Current Market Price
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="fab fa-bitcoin"></i>
            </div>
            <p class="card-category">BCH/USD</p>
            <h3 class="card-title"><%= @bch_last %></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> Current Market Price
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              <i class="fab fa-ethereum"></i>
            </div>
            <p class="card-category">ETH/USD</p>
            <h3 class="card-title"><%= @eth_last %></h3>
            <p></p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">local_offer</i> Current Market Price
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons">content_copy</i>
            </div>
            <p class="card-category">Accounts</p>
            <h3 class="card-title">    <%= Account.where(user_id: current_user.id).count %>

            </h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">warning</i>
              <a href="#">Get More ...</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              <i class="fa fa-angle-double-right"></i>
            </div>
            <p class="card-category">Deposits</p>
            <h3 class="card-title"><%= Deposit.where(user_id: current_user.id).count %></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">update</i> Just Updated
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              <i class="fa fa-angle-double-right"></i>
            </div>
            <h3 class="card-title"></h3>

              <%= link_to "Make A Deposit", new_deposit_path, class: "btn btn-warning" %>


          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">update</i> Just Updated
            </div>
          </div>
        </div>
      </div>
      </div>
      <div class="col-md-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Deposit History</h4>
            <p class="card-category">Previous Deposits</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">


    <tr>
      <th>Amount</th>
      <th>Payment type</th>
      <th>Email</th>
      <th> Status </th>

      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @deposits.each do |deposit| %>
      <tr>
        <td><%= deposit.amount %></td>
        <td><%= deposit.payment_type %></td>
        <td><%= deposit.email %></td>
        <td><% if deposit.status? %><a href="#" class="btn btn-success"> Paid</a> <%else %><a href="#" class="btn btn-danger">Not Confirmed</a> <% end %></td>

      </tr>
    <% end %>
    </tbody>
    </table>
    </div>
    </div>
    </div>

app/views/deposits/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">

      <div class="col-md-8 ml-md-3">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Make A Deposit</h4>
            <p class="card-category">New Deposit</p>
          </div>
          <div class="card-body" >

<%= render 'form', deposit: @deposit %>

</div>
</div>
</div>
</div>
</div>

app/views/deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @deposit.email %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @deposit.amount %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @deposit.payment_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @deposit.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @deposit.user %>
</p>

<%= link_to 'Edit', edit_deposit_path(@deposit) %> |
<%= link_to 'Back', deposits_path %>