config/routes.rb
Rails.application.routes.draw do
  resources :travels
  resources :welcomes
  mount Ckeditor::Engine => '/ckeditor'
  resources :deposits
  resources :menus
  resources :orders do
    resources :locations
  end
  #get 'orders/orders_index', to: 'orders#orders_index'

  resources :accounts
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root 'accounts#index', as: "authenticated_root"
  end
    root "welcomes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  require 'httparty'

  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/order.rb
class Order < ApplicationRecord
  extend FriendlyId
  friendly_id :tracking_number, use: :slugged

  belongs_to :user
  has_many :travels
before_validation :load_defaults

  def load_defaults
    if self.new_record?
      length = 8
      self.tracking_number = SecureRandom.random_number(10000000000)
      self.status = false
    end
  end
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user
  belongs_to :order

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable#, :confirmable, :lockable

has_many :deposits, dependent: :destroy
has_many :orders, dependent: :destroy
has_many :accounts, dependent: :destroy
end

app/models/welcome.rb
class Welcome < ApplicationRecord
  mount_uploader :logoimg, LogoimgUploader

end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
  layout "accounts"
  before_action :find_account, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :find_users, only: [:index, ]

  def index
    @users = User.where(user_id: current_user)
    @orders = Order.where(user_id: current_user).order('created_at DESC')
    @accounts = Account.where(user_id: current_user).order('created_at DESC')
    @deposits = Deposit.where(user_id: current_user).order('created_at DESC')
  end
  def show
  end
  def new
    @account = current_user.accounts.build
  end
  def create
    @account = current_user.accounts.build(account_params)
    @account.user_id = current_user.id
    if @account.save
      redirect_to root_path, notice: "Welcome "
    else
      render 'new', notice: "Please Try Again"
    end
  end

  def edit

  end

  def update
    if @account.update(account_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private
def find_account
  @account = Account.find(params[:id])

end

  def find_users
    if params[:id].nil?
      @user = current_user
    end
  end
    def account_params
      params.require(:account).permit(:first_name, :last_name, :city, :address, :country, :zipcode, :balance, :email, :phone_number, :user_id)
    end

end

app/controllers/menus_controller.rb
class MenusController < InheritedResources::Base
  before_action :find_menus, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_adminuser!, except: [:index, :show]
  def index
    @menus = Menu.all.order('created_at DESC')
  end

  def show
  end

  private
  def find_menus
    @menu = Menu.friendly.find(params[:id])
  end
    def menu_params
      params.require(:menu).permit(:title, :desc, :body)
    end

end

app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  layout "accounts", except: [:index, :show]
  before_action :find_order, only: [ :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_users, only: [:index]

  def index
    @orders = Order.all

    @search = params["search"]
  if @search.present?
    @tracking_number = @search["tracking_number"]
    @orders = Order.where(tracking_number: @tracking_number)
  end
end



  def show
  end
  def new
    @order = current_user.orders.build
  end
  def create
    @order = current_user.orders.build(order_params)
    @order.user_id = current_user.id
    if @order.save
      redirect_to root_path, notice: "Shipment Has Been Lodged Succesfully, We Will Proccess Your Order And Get Back To You Shortly "
    else
      render 'new', notice: "Please Try Again"
    end
  end

  def edit

  end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end

  private


  def find_users
    if params[:id].nil?
      @user = current_user
    end
  end
  def find_order
    @order = Order.friendly.find(params[:id])
  end

    def order_params
      params.require(:order).permit(:first_name, :last_name, :address, :zipcode, :city, :state, :country, :user_id, :phone_number, :slug, :message, :status, :tracking_number)
    end

end

app/controllers/travels_controller.rb
class TravelsController < InheritedResources::Base

  private

    def travel_params
      params.require(:travel).permit(:order_id, :user_id, :arrivaltime, :departtime, :location, :status, :departdate)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card">
    <div class="card-header card-header-warning">
      <h4 class="card-title">Set Pick Up Location </h4>
      <p class="card-category">Complete The Form</p>
    </div>

    <div class="card-body">
      <div class="row">

      </div>
          <div class="row">

            <div class="col-md-6">
              <%= f.input :address, required: true, autofocus: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :city, required: true, autofocus: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :state, required: true, autofocus: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :country, class: "form-control border-input", :as => :select, collection: ["Afghanistan",
            "Aland Islands",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua And Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegowina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo",
            "Congo, the Democratic Republic of the",
            "Cook Islands",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands (Malvinas)",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard and McDonald Islands",
            "Holy See (Vatican City State)",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran, Islamic Republic of",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, Democratic People's Republic of",
            "Korea, Republic of",
            "Kuwait",
            "Kyrgyzstan",
            "Lao People's Democratic Republic",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libyan Arab Jamahiriya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Macedonia, The Former Yugoslav Republic Of",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova, Republic of",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "Netherlands Antilles",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestinian Territory, Occupied",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russian Federation",
            "Rwanda",
            "Saint Barthelemy",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan, Province of China",
            "Tajikistan",
            "Tanzania, United Republic of",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Viet Nam",
            "Virgin Islands, British",
            "Virgin Islands, U.S.",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"],
             label: "Country" %>
            </div>
            <div class="col-md-6">
              <%= f.input :phone_number, class: "form-control border-input", required: true, autofocus: true %>
            </div>
            <div class="col-md-6">
              <%= f.input :zipcode, class: "form-control ",  required: true, autofocus: true %>
            </div>
          </div>


    <div class="row">
      <div class="col-md-12">
          <%= f.button :submit, "Add PickUp Location", class: "btn btn-warning" %>
      </div>
    </div>


<% end %>

app/views/accounts/edit.html.erb
<div class="content ml-md-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 push-2 ">
        <div class="pt-md-5 pb-md-5 mt-md-5 mb-md-4">
          <%= image_tag 'header/logo.png' %>

        </div>
<%= render 'form', account: @account %>

</div>
</div>
</div>
</div>

app/views/accounts/index.html.erb
<% if Account.where(user_id: current_user.id).exists?%>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <% @accounts.take(1).each do |a| %>



      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">store</i>
            </div>
            <p class="card-category">Revenue</p>
            <h3 class="card-title">$<%= a.balance %></h3>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">date_range</i>
  <%= link_to  new_deposit_path, class: "btn btn-warning" do %> <i class="fab fa-cc-amazon-pay"></i>  Top Up/Credit Yor Account <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">edit_location</i>
            </div>
            <p class="card-category"><%= link_to "PickUp Location", edit_account_path(a) %></p>

            <h3 class="card-title"></h3>

          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons">date_range</i>
              <%= link_to edit_account_path(a), class: "btn btn-warning"  do %>  <i class="fas fa-truck"></i>  PickUp Location <% end %>
            </div>
          </div>
        </div>
      </div>
      <% end %>


      <div class="col-lg-4 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons">local_shipping</i>
            </div>
            <p class="card-category">Send/Track Paackage</p>
            <h3 class="card-title"><%= Order.where(user_id: current_user.id).count %> Sent</h3>
          </div>
          <div class="card-footer">
            <div class="stats">
                <%= link_to new_order_path, class: "btn btn-warning" do %><i class="fas fa-truck-loading"> Send A Package  </i> <% end %>
            </div>
          </div>
        </div>
      </div>


    </div>
    <div class="row">

      <br>
      <div class="col-md-8 offset-md-3">
        <h3>Activities</h3>

        <ul class="timeline">
          <% @orders.each do |o| %>
            <li>
          <div class="card">
            <div class="card-body">



                <%= link_to o.tracking_number, o %>
                <a href="#" class="float-right">        <%= o.created_at.strftime("%d-%b-%Y") %>
                </a>
                <p>Address: <%= o.address %></p>
                <p>City: <%= o.city %></p>
                <p>State: <%= o.state %>, <%= o.country %></p>
                <%= link_to o, class: "btn btn-warning " do %>              <i class="material-icons">local_shipping</i> Track Shpment <% end %>

                <p class="float-right"><% if o.status? %><a href="#" class="btn btn-success">Awaiting Pickup</a> <%else %><a href="#" class="btn btn-danger">Out For Delivery</a> <% end %></p>



            </div>
          </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>
</div>
</div>


<% else %>

<div class="content ml-md-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 push-2 ">
        <div class="pt-md-5 pb-md-5 mt-md-5 mb-md-4">
          <br><br><br>
          <br><br><br>

            <br><br><br>
        </div>

        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Welcome </h4>
            <p class="card-category">Send A Package To Your Loved Ones And Friends</p>
          </div>

          <div class="card-body">
            <div class="text-center" style="padding-top:20px; padding-bottom:20px;">
              <%= link_to "Send A Package", new_account_path, class: "btn btn-warning" %>
              <br />
              <br />
              <%= link_to "Sign-out", destroy_user_session_path, method: :delete %>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/accounts/new.html.erb
<div class="content ml-md-5">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 push-2 ">
        <div class="pt-md-5 pb-md-5 mt-md-5 mb-md-4">
          <br><br><br>

          <br><br><br>

        </div>
<%= render 'form', account: @account %>

</div>
</div>
</div>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @account.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @account.last_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Country:</strong>
  <%= @account.country %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @account.zipcode %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @account.phone_number %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/menus/_form.html.erb
<%= simple_form_for(@menu) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :desc %>
    <%= f.input :body;text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Body;text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.title %></td>
        <td><%= menu.desc %></td>
        <td><%= menu.body;text %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @menu.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @menu.desc %>
</p>

<p>
  <strong>Body;text:</strong>
  <%= @menu.body;text %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/orders/_orders.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Shipment History</h4>
            <p class="card-category">Previous Shipments</p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">

    <tr>
      <th>Tracking number</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Zipcode</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.tracking_number %></td>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= order.address %></td>
        <td><%= order.zipcode %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= order.country %></td>
        <td><% if order.status? %><a href="#" class="btn btn-success"> Paid</a> <%else %><a href="#" class="btn btn-danger">Not Confirmed</a> <% end %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>
  </div>
  </div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<!--Breadcrumb start-->
<div class="ed_pagetitle">
<div class="ed_img_overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="page_title">
					<h2>Logistics That Works</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<ul class="breadcrumb">
					<li><a href="#l">home</a></li>
					<li>//</li>
					<li><a href="#">Current orders</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!--Breadcrumb end-->
<!--FAQ content start-->
<div class="ed_transprentbg ed_toppadder90 ed_bottompadder60">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">


        <div class="ed_transprentbg ">
        	<div class="container">
        		<div class="row">
        			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        				<div class="ed_counter_wrapper">
                  <% @orders.each do |o| %>
                  <div class="col-lg-8 col-md-8">
                    <div class="ed_chart_ratio style_2">
                      <i class="fa fa-ship" aria-hidden="true"></i>

                      <h4>Tracking Number: <%= link_to o.tracking_number, o %></h4>
                      <div class="well">
                        <p>Address: <%= o.address %></p>
                        <p>City: <%= o.city %></p>
                        <p>State: <%= o.state %>, <%= o.country %></p>
                      </div>
                      <p class="float-right"><% if o.status? %>
                        <%= link_to "View status", o, class: "btn btn ed_btn ed_orange" %>
                        <%else %>
                        <a href="#" class="btn btn-danger">Awaiting Pickup</a>
                        <% end %>
                      </p>


                                        </div>
                  </div>
                  <% end %>





        </div>
      </div>

    </div>
  </div>
</div>
</div>
</div>
</div>
</div>

app/views/orders/new.html.erb
<div class="content ">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 ">
        <div class="pt-md-1 pb-md-5 mt-md-5 mb-md-4">
          <br><br><br>
          <br><br><br>
        </div>
<%= render 'form', order: @order %>
</div>
</div>
</div>
</div>

app/views/orders/orders_index.html.erb
<%= render 'orders/orders' %>

app/views/orders/show.html.erb
<!--Breadcrumb start-->
<div class="ed_pagetitle">
	<div class="ed_img_overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="page_title">
					<h2><%= @order.tracking_number %></h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12">
				<ul class="breadcrumb">
					<li>  <%=  @order.first_name %>
					</li>
					<li>//</li>
					<li>  <%= @order.last_name %>
					</li>
					<li>//</li>
					<li><%= @order.package_size %> KG</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!--Breadcrumb end-->
<div class="ed_transprentbg ed_toppadder90 ed_bottompadder90">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="ed_blog_all_item">
					<div class="ed_blog_item ed_bottompadder50">
						<div class="ed_blog_info">
							<ul>
								<li><a href="#"><i class="fa fa-user"></i><%=  @order.first_name %>  <%= @order.last_name %> </a></li>
								<li><a href="#"><i class="fa fa-clock-o"></i>  <%= @order.created_at.strftime("%d-%b-%Y") %></a></li>
								<li><a href="#"><i class="fa fa-comment-o"></i>   Address: <%= @order.address %>, <%= @order.city %>, <%= @order.state %>
									<%= @order.zipcode %>, <%= @order.country %>

									<p><%= @order.phone_number %></p></a></li>
								</ul>
								<p>  <strong>Message:</strong>
									<%= raw(@order.message) %>

								</p>
								<p class="float-right"><% if @order.status? %>
								 <strong>Status:</strong>  <a href="#" class="btn btn-success">In Transit</a>
									<%else %>
									<a href="#" class="btn btn-danger">Awaiting Pickup</a>
									<% end %>
								</p>

							</div>
						</div>
					</div>
				</div>

			</div>
			<div class="row">
				<div class="container">
				    <div class="page-header">
				        <h1 id="timeline">Travel History</h1>
				    </div>
						<ul class="timeline">

				<%= render @order.travels.reverse %>
			</ul>

			</div>
		</div>
	</div>
</div>

app/views/travels/_travel.html.erb
                <li>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h5 class="panel-title"><small class="text-muted"><i class="far fa-clock"></i> </small><%=  travel.arrivaltime.to_datetime.strftime('%b %d %Y %I:%M%p')%></h5>
                    </div>
                    <div class="panel-body">
                      <p> <strong>Location:</strong> <%= travel.location %></p>
                      <p> <strong>Delivery Status:</strong> <%= travel.status %>.</p>
                      <p><small class="text-muted"><i class="fas fa-shipping-fast"></i> </small>,<strong>Next Depature Date/Time:</strong> <%=  travel.departdate.to_datetime.strftime('%b %d %Y %I:%M%p') %></p>
                    </div>
                  </div>
                </li>